name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.235.238.145
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/feedbacksense
            git fetch origin main
            git reset --hard origin/main
            export NVM_DIR="$HOME/.nvm"
            source ~/.nvm/nvm.sh
            npm install
            npm run build
            pm2 delete all || true
            pm2 start "npx next start -H 0.0.0.0 -p 3000" --name "feedbacksense"
