name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >> ~/.ssh/config << END
          Host ec2
            HostName 13.232.19.114
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy to EC2
        run: |
          ssh ec2 '
            cd /home/ubuntu/feedbacksense &&
            git fetch origin main &&
            git reset --hard origin/main &&
            export NVM_DIR="$HOME/.nvm" &&
            source ~/.nvm/nvm.sh &&
            npm install &&
            npm run build &&
            pm2 restart feedbacksense || pm2 start npm --name "feedbacksense" -- start
          '
