name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Adding Known Hosts
        run: ssh-keyscan -H 13.232.19.114 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.232.19.114 '
            cd /home/ubuntu/feedbacksense &&
            git pull origin main &&
            export NVM_DIR="$HOME/.nvm" &&
            source ~/.nvm/nvm.sh &&
            npm install &&
            npm run build &&
            pm2 restart all
          '
