name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.232.19.114
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Navigating to project directory..."
            cd /home/ubuntu/feedbacksense

            echo "Pulling latest changes..."
            git pull origin main

            echo "Setting up Node environment..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "Installing dependencies..."
            npm install

            echo "Building application..."
            npm run build

            echo "Restarting PM2..."
            pm2 restart all || pm2 start npm --name "feedbacksense" -- start
